# Generated by Django 3.2.7 on 2022-04-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='setor',
        ),
    ]
